version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  portal.application:
    image: ${DOCKER_REGISTRY-}portalapplication
    build:
      context: .
      dockerfile: src/Portal.Application/Dockerfile
    container_name: portal.application
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__Portal=Server=mssql;Database=PortalDb;User=sa;Password=Passw0rd!;TrustServerCertificate=True;
    ports:
      - "5000:5000"

  sale.generator:
    image: ${DOCKER_REGISTRY-}salegenerator
    build:
      context: .
      dockerfile: src/Sale.Generator/Dockerfile
    container_name: sale.generator
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__Portal=Server=mssql;Database=PortalDb;User=sa;Password=Passw0rd!;TrustServerCertificate=True;
